/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VocabularioRouteImport } from './routes/vocabulario'
import { Route as PersonalizarRouteImport } from './routes/personalizar'
import { Route as MemoriaRouteImport } from './routes/memoria'
import { Route as HabilidadesSociaisRouteImport } from './routes/habilidades-sociais'
import { Route as FonemasRouteImport } from './routes/fonemas'
import { Route as DesafiosRouteImport } from './routes/desafios'
import { Route as IndexRouteImport } from './routes/index'

const VocabularioRoute = VocabularioRouteImport.update({
  id: '/vocabulario',
  path: '/vocabulario',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonalizarRoute = PersonalizarRouteImport.update({
  id: '/personalizar',
  path: '/personalizar',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoriaRoute = MemoriaRouteImport.update({
  id: '/memoria',
  path: '/memoria',
  getParentRoute: () => rootRouteImport,
} as any)
const HabilidadesSociaisRoute = HabilidadesSociaisRouteImport.update({
  id: '/habilidades-sociais',
  path: '/habilidades-sociais',
  getParentRoute: () => rootRouteImport,
} as any)
const FonemasRoute = FonemasRouteImport.update({
  id: '/fonemas',
  path: '/fonemas',
  getParentRoute: () => rootRouteImport,
} as any)
const DesafiosRoute = DesafiosRouteImport.update({
  id: '/desafios',
  path: '/desafios',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/desafios': typeof DesafiosRoute
  '/fonemas': typeof FonemasRoute
  '/habilidades-sociais': typeof HabilidadesSociaisRoute
  '/memoria': typeof MemoriaRoute
  '/personalizar': typeof PersonalizarRoute
  '/vocabulario': typeof VocabularioRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/desafios': typeof DesafiosRoute
  '/fonemas': typeof FonemasRoute
  '/habilidades-sociais': typeof HabilidadesSociaisRoute
  '/memoria': typeof MemoriaRoute
  '/personalizar': typeof PersonalizarRoute
  '/vocabulario': typeof VocabularioRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/desafios': typeof DesafiosRoute
  '/fonemas': typeof FonemasRoute
  '/habilidades-sociais': typeof HabilidadesSociaisRoute
  '/memoria': typeof MemoriaRoute
  '/personalizar': typeof PersonalizarRoute
  '/vocabulario': typeof VocabularioRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/desafios'
    | '/fonemas'
    | '/habilidades-sociais'
    | '/memoria'
    | '/personalizar'
    | '/vocabulario'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/desafios'
    | '/fonemas'
    | '/habilidades-sociais'
    | '/memoria'
    | '/personalizar'
    | '/vocabulario'
  id:
    | '__root__'
    | '/'
    | '/desafios'
    | '/fonemas'
    | '/habilidades-sociais'
    | '/memoria'
    | '/personalizar'
    | '/vocabulario'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DesafiosRoute: typeof DesafiosRoute
  FonemasRoute: typeof FonemasRoute
  HabilidadesSociaisRoute: typeof HabilidadesSociaisRoute
  MemoriaRoute: typeof MemoriaRoute
  PersonalizarRoute: typeof PersonalizarRoute
  VocabularioRoute: typeof VocabularioRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vocabulario': {
      id: '/vocabulario'
      path: '/vocabulario'
      fullPath: '/vocabulario'
      preLoaderRoute: typeof VocabularioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personalizar': {
      id: '/personalizar'
      path: '/personalizar'
      fullPath: '/personalizar'
      preLoaderRoute: typeof PersonalizarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memoria': {
      id: '/memoria'
      path: '/memoria'
      fullPath: '/memoria'
      preLoaderRoute: typeof MemoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/habilidades-sociais': {
      id: '/habilidades-sociais'
      path: '/habilidades-sociais'
      fullPath: '/habilidades-sociais'
      preLoaderRoute: typeof HabilidadesSociaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fonemas': {
      id: '/fonemas'
      path: '/fonemas'
      fullPath: '/fonemas'
      preLoaderRoute: typeof FonemasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desafios': {
      id: '/desafios'
      path: '/desafios'
      fullPath: '/desafios'
      preLoaderRoute: typeof DesafiosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DesafiosRoute: DesafiosRoute,
  FonemasRoute: FonemasRoute,
  HabilidadesSociaisRoute: HabilidadesSociaisRoute,
  MemoriaRoute: MemoriaRoute,
  PersonalizarRoute: PersonalizarRoute,
  VocabularioRoute: VocabularioRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
